server.port=8080
spring.application.name=primer-parcial-progra-3

# Configuración para facilitar el desarrollo
logging.level.com.example.primerparcialprogra3=DEBUG
spring.main.allow-bean-definition-overriding=true
